services:
  db:
    container_name: database
    image: postgres:16.4
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment: # Used by the postgres image to setup a default user. For security reason, you should avoid using the postgres user
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  app:
    container_name: notebook-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    ports:
      - 4000:4000

volumes:
  pg-data:
    external: true # Must use "docker volume create --name=pg-data before
